services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: sma
      POSTGRES_PASSWORD: sma
      POSTGRES_DB: sma_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      # pg_isready by default tries to connect to a database with the same name
      # as the user (sma). The DB created in this compose is `sma_dev`, so
      # specify it explicitly to avoid repeated "database \"sma\" does not exist" logs.
      test: ["CMD-SHELL", "pg_isready -U sma -d sma_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:
