name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm -r build
      - run: pnpm -r test

  migrate:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && secrets.DATABASE_URL != ''
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --filter @apps/api
      - run: pnpm --filter @apps/api migrate:push
